# 3.1 Градиентный спуск

В этом задании нам предстоит реализовать классический алгоритм градиентного спуска для обучения модели логистической регрессии.

Алгоритм выполнения этого задания следующий:

* На основе частных производных, посчитанных на лекции, напишем функцию подсчета градиента бинарной кросс-энтропии по параметрам модели

* Напишем функцию обновления весов по посчитанным градиентам

* Напишем функцию тренировки модели

Замечание:
Тренировка модели проводится в несколько циклов, в рамках каждого из которых мы обновим веса модели, основываясь на предсказании для **каждого** объекта из датасета. Такие циклы называются *эпохами*. То есть одна эпоха - это набор обновлений весов, реализованный согласно посчитанным для каждого объекта из датасета ошибкам модели.

Вам необходимо реализовать обучение модели в несколько эпох. Их количество задается параметром функции. В рамках каждой эпохи необходимо пройти циклом по всем объектам обучающей выборки и обновить веса модели.

Шаблон кода для заполнения:

In [11]:
import numpy as np

np.random.seed(42)

def sigmoid(x: np.array, alpha: np.array):
        # TODO: напишите метод .predict(x) класса LinearRegression
        return 1/(1+np.exp(- x @ alpha))

# Функция подсчета градиента
def gradient(y_true: int, y_pred: float, x: np.array) -> np.array:
    """
    y_true - истинное значение ответа для объекта x
    y_pred - значение степени принадлежности объекта x классу 1, предсказанное нашей моделью
    x - вектор признакового описания данного объекта

    На выходе ожидается получить вектор частных производных H по параметрам модели, предсказавшей значение y_pred
    Обратите внимание, что размерность этого градиента должна получиться на единицу больше размерности x засчет своободного коэффициента a0
    """
    diff = np.array([ y_true_i - y_pred_i for y_true_i, y_pred_i in zip(y_true, y_pred)])
    grad = np.array(x.T()@diff)
    
    return grad


# Функция обновления весов
def update(alpha: np.array, gradient: np.array, lr: float):
    """
    alpha: текущее приближения вектора параметров модели
    gradient: посчитанный градиент по параметрам модели
    lr: learning rate, множитель перед градиентом в формуле обновления параметров
    """
    alpha_new = alpha + lr*gradient
    return alpha_new


# функция тренировки модели
def train(
    alpha0: np.array, x_train: np.array, y_train: np.array, lr: float, num_epoch: int
):
    """
    alpha0 - начальное приближение параметров модели
    x_train - матрица объект-признак обучающей выборки
    y_train - верные ответы для обучающей выборки
    lr - learning rate, множитель перед градиентом в формуле обновления параметров
    num_epoch - количество эпох обучения, то есть полных 'проходов' через весь датасет
    """
    alpha = alpha0.copy()
    for epo in range(num_epoch):
        y_pred = sigmoid(x_train, alpha)
        grad = gradient(y_train, y_pred, x_train)
        alpha = update(alpha, grad, lr)

    return alpha


In [22]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

X,y = load_iris(return_X_y=True)
X_train, y_train, X_test, y_test = train_test_split(X,y, test_size=0.3, shuffle=True, random_state=42, stratify=y)
print(*X[0:3], sep='\n')

[5.1 3.5 1.4 0.2]
[4.9 3.  1.4 0.2]
[4.7 3.2 1.3 0.2]


In [18]:
alpha = np.random.rand(4)
alpha

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [23]:
alpha = train(alpha, X_train, y_train, 0.01, 1000)

TypeError: 'numpy.ndarray' object is not callable

# Замечания:

1. В случае, если у Вас возникли сложности с выполнением первого задания и, как следствие, у Вас не выходит сделать это, мы рекомендуем подробно ознакомиться с главой **Производные $\frac{\partial H}{\partial \omega_i}$** нашей [лекции](https://colab.research.google.com/drive/1xjX_YnXcRr8HSiYLByMHxEIAADqs7QES?usp=sharing).

2. Обращайте внимание на названия и порядок аргументов в сдаваемых на проверку функциях - они должны совпадать с тем, что указано в шаблоне кода.

3. Обратите внимание, что матрица объект-признак в описании параметров функций обозначает переменную типа numpy.array(), каждый элемент которой - объект типа numpy.array() - вектор признаков соответствующего объекта.

4. Считайте, что свободный коэффициент a0 находится **в конце** списка alpha.